### ISSUE TITLE
makefile

### ISSUE THREAD

**Issue by hunterlong** [shandrapayne/JavaBasics#1]
[Makefile](https://opensource.com/article/18/8/what-how-makefile) allows you to [run](https://www.youtube.com/watch?v=tp1ZluX4aYs&t=0m25s) commands with ease, [like so...](https://www.youtube.com/watch?v=opj8IHkD97Q) <img width="20" src="https://media.giphy.com/media/i2oemhIwuZHIQ/giphy.gif"><img width="20" src="https://media3.giphy.com/media/A5M0iKWg8bxwk/source.gif">
- `make build` builds Docker image
- `make AddMeTogether` run the AddMeTogether java script
- `make ISBNChecksum` runs ISBNChecksum, etc etc etc

> `make build` is required first!

<p align="center">
<a href="https://www.youtube.com/watch?v=mLOdar3jshI&t=0m11s"><img src="https://user-images.githubusercontent.com/7519499/72577159-89639780-3886-11ea-925f-cb2d24ffdb77.gif"></a></p>

# `Makefile`: <img width="30" src="https://media.giphy.com/media/i2oemhIwuZHIQ/giphy.gif">
```sh
.PHONY: all AddMeTogether CalculateTip CompoundInterest ComputeTaxes GreatestCommonDivisor GuessingGame ISBNChecksum MinMax TheAdditionGame build

# Must run "make build" first, then any make command should work. example: "make ComputeTaxes".

build:
	docker build -t javabasics .

AddMeTogether:
	docker run -it -e SCRIPT='AddMeTogether' javabasics

CalculateTip:
	docker run -it -e SCRIPT='CalculateTip' javabasics

CompoundInterest:
	docker run -it -e SCRIPT='CompoundInterest' javabasics

ComputeTaxes:
	docker run -it -e SCRIPT='ComputeTaxes' javabasics

GreatestCommonDivisor:
	docker run -it -e SCRIPT='GreatestCommonDivisor' javabasics

GuessingGame:
	docker run -it -e SCRIPT='GuessingGame' javabasics

ISBNChecksum:
	docker run -it -e SCRIPT='ISBNChecksum' javabasics

MinMax:
	docker run -it -e SCRIPT='MinMax' javabasics

TheAdditionGame:
	docker run -it -e SCRIPT='TheAdditionGame' javabasics
```

# `Dockerfile`: <img width="30" src="https://media3.giphy.com/media/A5M0iKWg8bxwk/source.gif">
```docker
FROM java:8
ENV SCRIPT AddMeTogether
WORKDIR /app
COPY . .
CMD ["/app/startup.sh"]
```

# `startup.sh` <img width="30" src="https://media.giphy.com/media/i2oemhIwuZHIQ/giphy.gif">
##### (run `chmod +x startup.sh`)
```sh
#!/usr/bin/env sh
cd $SCRIPT
javac $SCRIPT.java
java $SCRIPT
```

Since I can't send a PR, add/create these 3 files and it [shall work](https://www.youtube.com/watch?v=5Ao5mg11xIk).

**Comment by shandrapayne** [comment]
AWESOME! Thanks for this!
